#![allow(unused_crate_dependencies)]

use satori_storage::EncryptionKey;

#[test]
fn test_generated_keys_are_valid() {
    // This is a key generated by the generate-key command in the format it outputs
    let config = r#"
kind = "hpke"
public_key = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VuAyEAZWyBUeaFatX3a3/OnqFljoEhAUHjrLgDJzzc5EqR/ho=
-----END PUBLIC KEY-----
"""
private_key = """
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VuBCIEIPAn/aQduWFV5VAlGQF79sBuzQItqFWu6FdJ4B77/UJ7
-----END PRIVATE KEY-----
"""
    "#;

    // Should be able to parse it
    let key: EncryptionKey = toml::from_str(config).expect("Failed to parse generated key");

    // Verify it's the correct variant
    match key {
        EncryptionKey::Hpke(_) => {
            // Success
        }
    }
}
