version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "clap"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
