[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = [ "https://github.com/rustsec/advisory-db" ]
ignore = [
  "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "MPL-2.0",
  "CC0-1.0",
  "ISC",
  "Unicode-3.0",
  "OpenSSL",
  "Zlib",
  "CDLA-Permissive-2.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "allow"
