# Build
FROM docker.io/library/rust:latest as builder

WORKDIR /app
COPY . .

RUN cargo build \
      --release \
      --package satorictl && \
    cp /app/target/release/satorictl /app/satorictl

# Runtime
FROM docker.io/library/debian:13-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tini \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/satorictl /app/satorictl

RUN mkdir -p /config && \
    mkdir -p /data

VOLUME /config
VOLUME /data

ENTRYPOINT ["/usr/bin/tini", "--", "/app/satorictl"]
