# Build
FROM docker.io/library/rust:latest as builder

WORKDIR /app
COPY . .

RUN cargo build --release --package satorictl

# Runtime
FROM docker.io/library/debian:13-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tini \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && \
    mkdir -p /config && \
    mkdir -p /data

COPY --from=builder /app/target/release/satorictl /app/satorictl

VOLUME /config
VOLUME /data

WORKDIR /data
ENTRYPOINT ["/usr/bin/tini", "--", "/app/satorictl"]
