{{- if .Values.eventProcessor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satori.fullname" . }}-event-processor
  labels:
    {{- include "satori.eventProcessor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.eventProcessor.replicaCount }}
  selector:
    matchLabels:
      {{- include "satori.eventProcessor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/event-processor-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "satori.eventProcessor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "satori.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: event-processor
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "satori.image" (dict "Chart" .Chart "Values" .Values "component" "satori-event-processor") }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --config
          - /config/config.toml
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.eventProcessor.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: {{ include "satori.fullname" . }}-event-processor
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "satori.fullname" . }}-event-processor
      {{- with .Values.eventProcessor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventProcessor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventProcessor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
