FROM docker.io/library/rust:bullseye as builder

RUN apt-get update && \
    apt-get install --yes \
      cmake

COPY . .
RUN cd event-processor && cargo install \
      --path . \
      --root /usr/local

FROM docker.io/library/debian:bullseye-slim

RUN apt-get update && \
    apt-get install --yes \
      tini

COPY --from=builder \
  /usr/local/bin/satori-event-processor \
  /usr/local/bin/satori-event-processor

ENV OBSERVABILITY_ADDRESS "0.0.0.0:9090"
EXPOSE 9090

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/satori-event-processor"]
