[package]
name = "satori-storage"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
async-channel.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
ciborium.workspace = true
futures.workspace = true
hpke.workspace = true
pem-rfc7468.workspace = true
rand.workspace = true
rust-s3.workspace = true
satori-common.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
ctor.workspace = true
hex.workspace = true
lazy_static.workspace = true
satori-testing-utils.workspace = true
tempfile.workspace = true
