# Build
FROM docker.io/library/rust:latest as builder

RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN cargo build \
      --release \
      --package satori-event-processor && \
    cp /app/target/release/satori-event-processor /app/satori-event-processor

# Runtime
FROM docker.io/library/debian:13-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tini \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/satori-event-processor /app/satori-event-processor

ENV OBSERVABILITY_ADDRESS=0.0.0.0:9090
EXPOSE 9090/tcp

ENTRYPOINT ["/usr/bin/tini", "--", "/app/satori-event-processor"]
