---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  # formatting-and-quality:
  #   name: Formatting and Quality
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: cachix/install-nix-action@v31
  #     - uses: cachix/cachix-action@v16
  #       with:
  #         name: devenv
  #     - name: Install devenv.sh
  #       run: nix profile install nixpkgs#devenv

  #     - name: Format
  #       shell: devenv shell bash -- -e {0}
  #       run: treefmt --fail-on-change

  #     - name: cargo-deny
  #       shell: devenv shell bash -- -e {0}
  #       run: cargo deny check

  #     - name: Clippy
  #       shell: devenv shell bash -- -e {0}
  #       run: cargo clippy --all-targets -- -D warnings

  #     - name: Build
  #       shell: devenv shell bash -- -e {0}
  #       run: cargo build --all-targets

  #     - name: Tests
  #       shell: devenv shell bash -- -e {0}
  #       run: cargo test

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: cachix/install-nix-action@v31
  #     - uses: cachix/cachix-action@v16
  #       with:
  #         name: devenv
  #     - name: Install devenv.sh
  #       run: nix profile install nixpkgs#devenv

  #     - name: Integration tests
  #       shell: devenv shell bash -- -e {0}
  #       run: cargo test integration_tests -- --ignored --test-threads=1

  container-images:
    name: Container Images
    # needs:
    #   - formatting-and-quality
    #   - integration-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - satori-agent
          - satori-archiver
          - satori-event-processor
          - satorictl

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build container image
        run: buildah bud -f "${{ matrix.package }}/Containerfile" -t "${{ matrix.package }}:latest" .

      # TODO
      # - name: Push container image
      #   if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
      #   run: |
      #     set -x

      #     # Build image via Nix and take the resulting path as the local container registry
      #     local_cr="docker-archive://$(nix build .#-container-image --no-link --print-out-paths)"

      #     # The container registry to push images to (GHCR)
      #     remote_cr="docker://ghcr.io/dannixon/${{ matrix.package }}"
      #     remote_cr_creds="${{ github.repository_owner }}:${{ github.token }}"

      #     # Push image using the Git ref name as the image tag (i.e. "main" or the tag name)
      #     skopeo copy --dest-creds="$remote_cr_creds" "$local_cr" "$remote_cr:${{ github.ref_name }}"

      #     # Push image using the Git SHA as the image tag
      #     skopeo copy --dest-creds="$remote_cr_creds" "$local_cr" "$remote_cr:${{ github.sha }}"

      #     # If the trigger was a tag (i.e. a release)
      #     if [[ "${{ github.ref_type }}" == 'tag' ]]; then
      #       # Push image using the "latest" tag
      #       skopeo copy --dest-creds="$remote_cr_creds" "$local_cr" "$remote_cr:latest"
      #     fi
