---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  formatting-and-quality:
    name: Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Format
        shell: devenv shell bash -- -e {0}
        run: treefmt --fail-on-change

      - name: cargo-deny
        shell: devenv shell bash -- -e {0}
        run: cargo deny check

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: cargo build --all-targets

      - name: Tests
        shell: devenv shell bash -- -e {0}
        run: cargo test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Integration tests
        shell: devenv shell bash -- -e {0}
        run: cargo test integration_tests -- --ignored --test-threads=1

  container-images:
    name: Container Images
    needs:
      - formatting-and-quality
      - integration-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - satori-agent
          - satori-archiver
          - satori-event-processor
          - satorictl

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build container image
        run: buildah build -f "${{ matrix.package }}/Containerfile" -t "${{ matrix.package }}:latest" .

      - name: Push container image
        if: (github.ref_name == 'main' || github.ref_type == 'tag') && github.repository == 'DanNixon/satori'
        env:
          PACKAGE: ${{ matrix.package }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REF_TYPE: ${{ github.ref_type }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_SHA: ${{ github.sha }}
        run: bash .github/workflows/push-container-images.sh
