[cameras."test one"]
hls_url = "http://one:9999/stream.m3u8"
thumbnail_url = "http://one:9999/jpeg"
mjpeg_url = "http://one:9999/mjpeg"

[cameras."test two"]
hls_url = "http://two:9999/stream.m3u8"
thumbnail_url = "http://two:9999/jpeg"
mjpeg_url = "http://two:9999/mjpeg"
